services:
  - type: web
    name: pharma-b2b-backend
    env: node
    buildCommand: cd backend && npm install && npx prisma db push && npx prisma generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: "3001"
